version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: local.Dockerfile
    image: cfp-energy
    container_name: cfp-energy-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - cfp-energy-network

  db:
    image: mysql:8.3.0
    container_name: cfp-energy-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - cfp-energy-network

  nginx:
    image: nginx:stable-alpine3.17
    container_name: cfp-energy-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - cfp-energy-network

networks:
  cfp-energy-network:
    driver: bridge
